[package]
name = "libhootc"
version = "0.1.0"
authors = ["Benjamin Thomas (Aviansie Ben) <ben@benthomas.ca>"]

[features]
"default" = ["smallvec/union"]

[dependencies]
"itertools" = "0.7.3"
"lazy_static" = "1.1.0"
"plex" = "0.2.3"
"smallvec" = "0.6.7"
